name: rover_dashboard
description: Graphical application for remotely operating the rover.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2025.4.25+21  # Always increment the build number, never go down, even on new versions

environment:
  sdk: ^3.5.0

# Prefer to use `flutter pub add packageName` rather than modify this section by hand.
dependencies:
  flutter:
    sdk: flutter
  burt_network:
    git:
      url: https://github.com/BinghamtonRover/Rover-Code.git
      path: burt_network
      ref: 2.7.0
  file_picker: ^8.0.0+1
  fl_chart: ^0.69.0
  flutter_libserialport: ^0.6.0
  package_info_plus: ^8.0.0
  flutter_resizable_container: ^3.0.2
  path_provider: ^2.0.14
  protobuf: ^3.0.0
  url_launcher: ^6.1.10
  just_audio: ^0.9.42
  collection: ^1.18.0
  flutter_sdl_gamepad: ^1.1.3
  just_audio_windows: ^0.2.2
  coordinate_converter: ^1.2.3
  archive: ^4.0.7
  image: ^4.5.4

# Prefer to use `flutter pub add --dev packageName` rather than modify this section by hand.
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  msix: ^3.16.9
  very_good_analysis: ^6.0.0

dependency_overrides:
  flutter_sdl_gamepad:
    git:
      url: https://github.com/BinghamtonRover/flutter_sdl_gamepad.git
      ref: 65e33a1deb186f137200d2723b25fa8e847f4e71

# Generates icons for the given platforms
#   Run: dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  linux:
    generate: true

# Builds a Windows .msix App Installer file for the Dashboard.
#   Command: dart run msix:create
msix_config:
  msix_version: 2025.2.12.20
  display_name: Dashboard
  publisher_display_name: Binghamton University Rover Team
  identity_name: edu.binghamton.rover
  logo_path: assets/logo.png
  trim_logo: false
  capabilities: internetClientServer, privateNetworkClientServer, usb, serialcommunication, lowLevel
  output_name: Dashboard
  certificate_path: windows_certificate.pfx
  certificate_password: rover
  install_certificate: false  # needed so GitHub CLI doesn't try to install the certificate

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/rover.png
    - assets/clippy.webp
    - assets/bad_apple.zip
    - assets/bad_apple_thumbnail.webp
    - assets/bad_apple2.mp3
    - assets/binghamton2.wav
    - assets/Rocks_Minerals_Images/
