name: Documentation

# Documents the Dart code within this project with the `dartdoc` tool.
# Publishes the result to a separate branch, `documentation`, under the `docs` folder. 
# Set GitHub pages to publish that target to get an online documentation site. 

on:
  push:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-22.04
    steps:
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/linux

      - name: Clone repo
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          submodules: recursive

      - name: Git Setup
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git branch --all
          git switch --track origin/documentation
          git reset --hard origin/main

      - name: Add Flutter to path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Setup 
        run: |
          flutter packages get
          flutter pub global activate dartdoc
          flutter pub global run dartdoc --version
          flutter --version

      - name: Analyze code
        run: |
          flutter analyze --dartdocs

      - name: Output error
        if: failure()
        run: echo "::error The code or is missing documentation. Run flutter analyze --dartdocs"

      - name: Generate documentation
        run: flutter pub global run dartdoc --ignore 'unresolved-doc-reference,not-implemented,no-documentable-libraries,ambiguous-reexport' --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:html,dart:js,dart:ffi,dart:js_util' --quiet --json --output docs --no-validate-links --no-verbose-warnings --no-allow-non-local-warnings
        
      - name: Commit and push files
        run: |
          cd docs
          cd ..
          git status
          git stage --force docs
          git commit -a -m "Generated documentation"
          git push --force
